### ISSUE TITLE
/bin/bash in latest image

### ISSUE THREAD

**Issue by grenotjg** [hashicorp/docker-hub-images#92]
Hi,

Since last update, my gitlab runner seems to encounter a problem.
I'm using packer light install and bash isn't found anymore.

```yaml
build_image:
  stage: build
  image:
    name: hashicorp/packer:light
    entrypoint: ["/bin/sh", "-c"]
  script:
    - /bin/bash scripts/build.sh
```

Result :
`sh: eval: line 99: /bin/bash: not found`

bash is present in version 1.5.1
